### ISSUE TITLE
Newline chars still printed in the inline mode.

### ISSUE THREAD

**Issue by jluzny** [timfayz/pretty#1]
Thanks @timfayz for the inline mode.

When using this mode, I can still see two newline chars being added to the end of the dumped string. It would be nice to avoid it.

**Comment by timfayz** [comment]
Appreciate it @jluzny! 

This is the intended behaviour. Have you tried `.empty_line_at_end = false`? It is true by default because, as the option says, it is used to "stack up" (ie. separate visually) multiple prints.

> it would be nice to avoid it.

Why btw? Can you share a case where it is annoying?

**Comment by jluzny** [comment]
I'm also using pretty for dumping values into a string, which is then passed for logging to [log.zig](https://github.com/karlseguin/log.zig).
In this use case, any newline char is not welcome. 
Using `.empty_line_at_end` removed one occurrence of `\n` but there is still one remaining.

Please see the full test code:
```
const TestStruct = struct {
    msg: []const u8,
};
const test_struct = TestStruct{ .msg = "Hello Struct" };
const test_string = "Hello String";

std.log.debug("STD LOG {s}", .{test_string});
std.log.debug("STD LOG {}", .{test_struct});

const string_out = try pretty.dump(ally, test_string, .{ .show_type_names = true, .inline_mode = true, .empty_line_at_end = false });
defer ally.free(string_out);
std.log.debug("PRETTY LOG {s}", .{string_out});
logz.info().string("test_string", string_out).log();

const struct_out = try pretty.dump(ally, test_struct, .{ .show_type_names = false, .inline_mode = true, .empty_line_at_end = false });
defer ally.free(struct_out);
std.log.debug("PRETTY LOG {s}", .{struct_out});
logz.info().string("test_struct", struct_out).log();
```

and the output:


```
debug: STD LOG Hello String
debug: STD LOG example.main.TestStruct{ .msg = { 72, 101, 108, 108, 111, 32, 83, 116, 114, 117, 99, 116 } }
debug: PRETTY LOG *const [12:0]u8 = "Hello String"

@ts=1709452695670 @l=INFO test_string="*const [12:0]u8 = \"Hello String\"\n"
debug: PRETTY LOG .{ .msg: "Hello Struct" }

@ts=1709452695670 @l=INFO test_struct=".{ .msg: \"Hello Struct\" }\n"
```

**Comment by timfayz** [comment]
Hm...you're right. This is annoying. I think `dump` should simply produce a "raw" output without extra bells (newlines).

**Comment by timfayz** [comment]
To be honest, I'm not sure how to handle this extra lines stuff across provided methods.

What you think if I redesign as follows:
- `dump*` methods do not add any extra newlines at the end.
- `print*` methods stay the same: they add a single newline + extra due to `.empty_line_at_end` is on by default.
- However, introduce `.fmt` option to tweak the output of print/dump methods however we like.
Note, `.fmt` will have a precedence over any other option responsible for pre/post-fixing stuff (now or in the future).

Example of using `.fmt`:
```zig
try pretty.print(alloc, "Hello world", .{ .fmt = "PRETTY OUTPUT:\n{s}\n"});
```
Output:
```
$ zig run main.zig
PRETTY OUTPUT:
*const [12:0]u8 = "Hello String"
$ 
```
In case of dump:
```zig
try pretty.dump(alloc, "Hello world", .{ .fmt = "PRETTY OUTPUT:\n{s}\n"});
```
Output:
```
PRETTY OUTPUT:\n*const [12:0]u8 = "Hello String"\n
```

**Comment by jluzny** [comment]
Absolutely, I like the idea of having different newline defaults for dump and print methods.
Plus the fmt variant to tweak/ customise as needed!

**Comment by timfayz** [comment]
@jluzny, check out the latest version (v0.9.3) and the new option `.fmt`. Also, I've decided to set `.empty_line_at_end = false` by default to avoid potential confusion from users. So, as proposed:

- `dump*` methods add no extra newlines to the output.
- `print*` methods add a single newline + extra newline if `.empty_line_at_end = true`.
- `.fmt` option is now available to tweak the resulting dump/print output by applying `.fmt = "pre{s}post"`

**Comment by jluzny** [comment]
@timfayz I run the basic tests of modified dump, print and new .fmt option, and seems to works fine! :-)
Thanks a lot for the instant improvements!
