### ISSUE TITLE
Build instructions from README are out of date

### ISSUE THREAD

**Issue by schmee** [timfayz/pretty#11]
Hi, thank you for this project, it's really useful! 👍 

As it stands, the installation instructions in the README don't work:

```
$ zig fetch --save https://github.com/timfayz/pretty/archive/v0.10.3.tar.gz
error: bad HTTP response code: '404 Not Found'
```

The issue is that the v0.10.3 tag is not pushed, the most recent one is v0.10.2 (see [here](https://github.com/timfayz/pretty/tags))

So ideally, you could push tag v0.10.3 or the README should be updated to use the most recent existing tag (v0.10.2). Thanks!

**Comment by timfayz** [comment]
You're right! Totally missed it. Thank you! 
*Now, it should work as expected.
