### ISSUE TITLE
Fails to compile if `max_depth` option is 0 and printed type is recursive

### ISSUE THREAD

**Issue by DanikVitek** [timfayz/pretty#4]
Zig version `0.12.0`

![image](https://github.com/timfayz/pretty/assets/25585136/0edebb49-61f6-40a9-9598-41c780fba7f4)

**Comment by DanikVitek** [comment]
https://github.com/DanikVitek/monkey-lang/commit/a7718d5b68671b487dcebbcefa0cd5af0d314164

**Comment by timfayz** [comment]
Thank you for reporting. Unfortunately, the last time I tried 0 I experienced the build failure myself. I couldn't figure out why because all conditions were written correctly. I assume it its related to some comptime issues specific to zig. I'll try to investigate it with the latest zig version again and ping you when it's done.

**Comment by DanikVitek** [comment]
Seems to be some sort of infinite comptime loop. When I tried setting the value to `255`, the compilation time became really slow

**Comment by timfayz** [comment]
Unfortunately, I can't reproduce the failure with `$ zig version -> 0.12.0`. Could you give a use case where it happens?

**Comment by DanikVitek** [comment]
This problem does not arise for non-recursive types.
Minimal reproducible example:
```zig
const A = union(enum) {
    int: u8,
    a: *const @This(),
};
try pretty.print(alloc, A{ .int = 10 }, .{ .max_depth = 0 });
```

**Comment by timfayz** [comment]
Thank you. Yes, that needs to be fixed. I'll look at it the other day as I was unable to fix it quick and zig just sigfaults without reporting anything. Overall, other than specifying `max_depth`, pretty doesn't have any logic to protect you from falling into infinite recursive traversal (which probably was your case, ie. traversing an ast with descending nodes pointing to the ones of its ancestors). However, in the example you provided, even though the definition is recursive, the value is not. This makes a little clue that the problem should happen in comptime while zig attempts to construct a call chain by unrolling union tags.

**Comment by timfayz** [comment]
After yesterday's investigation, I couldn't find why zig crashes. People on [ziggit](https://ziggit.dev/t/comptime-segfault-on-recursive-types/4289) discussed different ideas, but nothing helped. I think the only way (the hard way) left is to simply rewrite the whole traversing logic as I originally wanted before the v1 release. So, who knows how much time it will take. In a meantime, I recommend writing a custom traversal tailored to your particular parse tree.
